app/main/routes.py


from flask import render_template, request, Blueprint

from app.models import Post

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
	page = request.args.get(key='page', type=int, default=1)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page)
	return render_template('home.html', posts=posts)


@main.route('/about')
def about():
	return render_template('about.html', title='About')

app/posts/routes.py
from flask import render_template, request, redirect, flash, url_for, Blueprint, abort

from app.models import Post, User

from app.posts.forms import PostForm

from flask_login import login_required, current_user

from app import db



posts = Blueprint('posts', __name__)

@posts.route('/post', methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user)
		db.session.add(post)
		db.session.commit()
		flash('Your shit is posted', 'success')
		return redirect(url_for('main.home'))
	return render_template('new_post.html',title='New Post',form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def read_post(post_id):
	post = Post.query.get_or_404(post_id)
	return render_template('read_post.html',title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'] )
@login_required
def update_post(post_id):
	post = Post.query.get_or_404(post_id)
	if post.author!=current_user:
		abort(403)

	form = PostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.content = form.content.data
		db.session.commit()
		flash('Your post has been updated!','success')
		return redirect(url_for('posts.read_post',post_id=post.id))
	elif request.method == 'GET':
		form.title.data = post.title
		form.content.data = post.content
	return render_template('new_post.html',title='Update Post',form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

@posts.route('/user/<string:username>')
def user_posts(username):
	page = request.args.get(key='page', type=int, default=1)
	user = User.query.filter_by(username=username).first_or_404()
	posts = Post.query.filter_by(author=user)\
		.order_by(Post.date_posted.desc())\
		.paginate(per_page=5, page=page)
	return render_template('user_posts.html', posts=posts, user=user )

app/users/routes.py
from flask import render_template, flash, redirect, url_for, request, Blueprint

from app.users.forms import SignupForm, LoginForm, UpdateAccountForm, RequestPasswordResetForm, PasswordResetForm

from flask_login import login_required, login_user, logout_user, current_user

from app import db, bcrypt

from app.models import User, Post

from app.users.utils import save_picture, send_reset_mail

users = Blueprint('users',__name__)

@users.route('/signup', methods=['GET', 'POST'])
def signup():
	form = SignupForm()

	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data,email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Account Created.Login to explore!', 'success')
		return redirect(url_for('users.login'))

	return render_template('signup.html', title='Signup', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
	form = LoginForm()

	if form.validate_on_submit():

		user = User.query.filter_by(email=form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			flash(f'Logged in successfully. Have fun {user.username}!', 'success')

			next_page = request.args.get('next')
			return redirect(next_page) if next_page else  redirect(url_for('main.home'))
		else:
			flash(f'Login unsuccessful.Please check your email and password', 'danger')
	return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
	logout_user()
	flash(f'Logged out successfully!','success')
	return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
	form = UpdateAccountForm()

	#During GET method if won't be executed.
	if form.validate_on_submit():
		if form.picture.data:
			current_user.image_file = save_picture(form.picture.data)
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Changes made!','success')
		form.username.data = current_user.username 
		form.email.data = current_user.email
		return redirect(url_for('users.account'))

	#During GET method elif will be executed.
	elif request.method == 'GET':
		form.username.data = current_user.username 
		form.email.data = current_user.email

	image_file = url_for('static',filename=f'profile_pics/{current_user.image_file}')
	return render_template('account.html',title='Account',image_file_path=image_file, form=form)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestPasswordResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_mail(user)
		flash('A password reset verification link has been sent your email.Please verify your mail', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html',title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))

	user = User.verify_reset_token(token)
	if user is None:
		flash('The link is invalid or expired','warning')
		return redirect(url_for('users.password_reset_request'))
	form = PasswordResetForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password = hashed_password
		db.session.commit()
		flash(f'Your password has been changed', 'success')
		return redirect(url_for('users.login'))

	return render_template('reset_password.html', title='Reset Password', form=form)

app/templates/about.html
{% extends 'layout.html' %}


{% block content %}

<h1>About Page</h1>

{% endblock %}


app/templates/account.html
{% extends 'layout.html' %}


{% block content %}

<div class='content-section'>
	

	<!-- Account Profile -->

	<div class='media'>
		<img class='rounded-circle account-img' src='{{image_file_path}}'>
		<div class='media-body'>
			<h2 class='account-heading'>{{current_user.username}}</h2>
			<p class='text-secondary'>{{current_user.email}}</p>
		</div>
	</div>


	<!-- Account Updation Form -->

	<form method='POST' action='' enctype='multipart/form-data'>

		{{ form.hidden_tag() }}

		<fieldset class='form-group'>

			<legend class='border-bottom mb-4'>Account Info</legend>

			<!-- Username Field -->

			<div class='form-group'>
				{{form.username.label(class='form-control-label')}} 
				
				{% if form.username.errors %}
				{{ form.username(class='form-control form-control-lg is-invalid') }}
				<div class='invalid-feedback'>
					{% for error in form.username.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.username(class='form-control form-control-lg') }}
				{% endif %}
			</div>

			<!-- Email Field -->

			<div class='form-group'>
				{{form.email.label(class='form-control-label')}}
				
				{% if form.email.errors %}
				{{ form.email(class='form-control form-control-lg is-invalid') }}
				<div class='invalid-feedback'>
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class='form-control form-control-lg') }}
				{% endif %}
			</div>

			<!-- Picture Field -->

			<div class='form-group'>
				{{form.picture.label()}}
				{{form.picture(classs='form-control-file')}}
				<br>
				{% if form.picture.errors %}
					{% for error in form.picture.errors %}
						<span class='text-danger'>{{error}}</span>
					{% endfor %}
				{% endif %}
			</div>

		</fieldset>

		<small><a href="{{ url_for('users.password_reset_request') }}">Reset Password</a></small>

		<!-- Submit Field -->

		<div class='form-group'>
			{{form.submit(class='btn btn-outline-info')}}
		</div>

	</form>
</div>

{% endblock %}

app/templates/home.html
{% extends 'layout.html' %}



{% block content %}

{% for post in posts.items %}
<article class="media content-section">

	<!-- Aritcle Author Profile Picture -->
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
	
	<div class="media-body">

		<div class="article-metadata">

			<!-- Author Name And Post Dated -->
			<a class="mr-2" href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>

		</div>

		<!-- Post Title And Content -->
		<h2><a class="article-title" href="{{ url_for('posts.read_post',post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	
	</div>

</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
	{% if page_num %}
		{% if posts.page == page_num %}
			<a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
		{% else %}
			<a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
		{% endif %}
	{% else %}
	  ...
	{% endif %}
{% endfor %}

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Bootstrap Nav Bar Icon CSS -->
    <link rel="stylesheet" type="text/css"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Local CSS -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">


    <!-- Tab Title and Favicon -->
    {% if title %}
    <title>Flask - {{title}}</title>
    {% else %}
    <title>Flask Home</title>
    {% endif %}

</head>

<body>

    <!-- Nav Bar -->
    <header class="site-header">

        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{url_for('main.home')}}">Flask Book</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">

                <span class="navbar-toggler-icon"></span>

            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">

                <!-- NavBar Lef Side -->
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{url_for('main.home')}}">
                        <div class="icon">
                            <i class="fa fa-home" aria-hidden="true"></i> Home 
                        </div>
                    </a>

                    <a class="nav-item nav-link" href="{{url_for('main.about')}}">
                        <div class="icon">
                            <i class="fa fa-file-text-o" aria-hidden="true"></i> About
                        </div>
                    </a>
                </div>


                <!-- Navbar Right Side -->
                <div class="navbar-nav">

                    {% if current_user.is_authenticated %}

                    <a class="nav-item nav-link" href="{{url_for('posts.new_post')}}">
                     <div class="icon">
                        <i class="fa fa-pencil"></i> New Post
                    </div> 
                </a>

                <a class="nav-item nav-link" href="{{url_for('users.account')}}">
                    <div class="icon">
                        <i class="fa fa-user"></i> Account Info
                    </div>
                </a>

                <a class="nav-item nav-link" href="{{url_for('users.logout')}}">
                    <div class="icon">
                        <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                    </div>
                </a>

                {% else %}
                <a class="nav-item nav-link" href="{{url_for('users.login')}}">
                    <div class="icon">
                        <i class="fa fa-sign-in" aria-hidden="true"></i> Login
                    </div>

                    <a class="nav-item nav-link" href="{{url_for('users.signup')}}">
                        <div class="icon">
                            <i class="fa fa-user-plus" aria-hidden="true"></i> Signup
                        </div>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>



<!-- Main Page Body -->
<main role="main" class="container">

    <div class="row">

        <!-- To flash messages -->
        <div class='col-md-8'>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class='alert alert-{{ category }}'>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <!-- Body of particular webpage  -->
            {% block content %}{% endblock %}
        </div>


        <!-- Side Bar -->
        <div class="col-md-4">
            <div class='content-section'>
                <h3>Sidebar</h3>
                <p class='text-muted'>Site on construction y'all!Fuck outta here!!
                    <ul class='list-group'>
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</main>


<!-- Jquery Javascript -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
crossorigin="anonymous"></script>

<!-- Popper Javascript -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
crossorigin="anonymous"></script>

<!-- Bootstrap JavaScript -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
crossorigin="anonymous"></script>

</body>

</html>

app/templates/login.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">
	<form method="POST" action="">
		{{ form.hidden_tag() }}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Join Now</legend>

			<!-- Email -->
			<div class="form-group">
				{{form.email.label(class="form-control-label")}}
				{% if form.email.errors %}
				{{ form.email(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.email(class="form-control form-control-lg") }}
				{% endif %}
			</div>

			<!-- Password -->
			<div class="form-group">
				{{form.password.label(class="form-control-label")}}
				{% if form.password.errors %}
				{{ form.password(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.password(class="form-control form-control-lg") }}
				{% endif %}
			</div>
			<div class="form-check">
				{{ form.remember(class="form-check-input")}}
				{{ form.remember.label(class="form-check-label")}}
			</div>

		</fieldset>

		<div class="form-group">
			{{form.submit(class="btn btn-outline-info")}}

			<small><a href="{{ url_for('users.reset_request') }}">Forgot Password?</a></small>

		</div>

	</form>
</div>


<div>
	<small class="text-muted">
		Need an Account? <a class="ml-2" href="{{url_for('users.signup')}}">Signup</a>
	</small>
</div>

{% endblock %}




app/templates/new_post.html
{% extends 'layout.html' %}


{% block content %}


<div class="content-section">

	<form method="POST" action="">

		{{ form.hidden_tag() }}

		<fieldset class="form-group">

			<legend class="border-bottom mb-4">{{ legend }}</legend>

			<!-- Title -->
			<div class="form-group">
				
				{{form.title.label(class="form-control-label")}}
				
				{% if form.title.errors %}
				{{ form.title(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.title.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.title(class="form-control form-control-lg") }}
				{% endif %}

			</div>


			<!-- Content -->
			<div class="form-group">
				
				{{form.content.label(class="form-control-label")}}

				{% if form.content.errors %}
				{{ form.content(class="form-control form-control-lg is-invalid") }}
				<div class="invalid-feedback">
					{% for error in form.content.errors %}
					<span>{{ error }}</span>
					{% endfor %}
				</div>
				{% else %}
				{{ form.content(class="form-control form-control-lg") }}
				{% endif %}

			</div>


		</fieldset>

			<!-- Submit -->
			<div class="form-group">
				{{form.submit(class="btn btn-outline-info")}}
			</div>

	</form>
</div>


{% endblock %}

app/templates/read_post.html
{% extends 'layout.html' %}



{% block content %}


<article class="media content-section">

	<!-- Aritcle Author Profile Picture -->
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
	
	<div class="media-body">

		<div class="article-metadata">
			
			<!-- Author Name And Post Dated -->
			<a class="mr-2" href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>

		</div>

		<!-- Post Title And Content  -->
		<h2><a class="article-title" href="{{ url_for('posts.read_post',post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>

		<!-- Update And Delete Links If A User Is Logged In -->
		{% if post.author == current_user %}
		<div>
			<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
			<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
		</div>
		{% endif %}

	</div>

</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
					<input class="btn btn-danger" type="submit" value="Delete">
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock %}

app/templates/reset_password.html
{% extends 'layout.html' %}

{% block content %}
<div class='content-section'>

    <form method='POST' action=''>
        
        {{ form.hidden_tag() }}

        <fieldset class='form-group'>

            <legend class='border-bottom mb-4'>Reset Password</legend>

            <!-- Password Field -->

            <div class='form-group'>
                {{form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class='form-control form-control-lg') }}
                {% endif %}
            </div>

            <!-- Confirm Password Field -->

            <div class='form-group'>
                {{form.confirm_password.label(class='form-control-label')}}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class='form-control form-control-lg') }}
                {% endif %}
            </div>
        </fieldset>

        <!-- Submit Field -->

        <div class='form-group'>
            {{form.submit(class='btn btn-outline-info')}}
        </div>
    </form>
</div>


{% endblock %}




app/templates/reset_request.html
{% extends 'layout.html' %}

{% block content %}

<div class="content-section">

    <form method="POST" action="">
        
        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            
            <legend class="border-bottom mb-4">Reset Password</legend>

            <!-- Email -->
            <div class="form-group">
                {{form.email.label(class="form-control-label")}}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>

        </fieldset>
        
        <!-- Submit -->
        <div class="form-group">
            {{form.submit(class="btn btn-outline-info")}}
        </div>

    </form>
</div>


{% endblock %}

app/templates/signup.html
{% extends 'layout.html' %}

{% block content %}
<div class='content-section'>

    <form method='POST' action=''>
        
        {{ form.hidden_tag() }}

        <fieldset class='form-group'>

            <legend class='border-bottom mb-4'>Join Now</legend>

            <!-- Username Field -->

            <div class='form-group'>
                {{form.username.label(class='form-control-label')}} 
                
                <!--<label for='username' class='form-control-label'>Username</label> -->
                
                {% if form.username.errors %}
                {{ form.username(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                
                <!-- <input name='form.username.data' type='text' id='username' -->
                
                {{ form.username(class='form-control form-control-lg') }}
                {% endif %}
            </div>

            <!-- Email Field -->

            <div class='form-group'>
                {{form.email.label(class='form-control-label')}}
                {% if form.email.errors %}
                {{ form.email(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg') }}
                {% endif %}
            </div>

            <!-- Password Field -->

            <div class='form-group'>
                {{form.password.label(class='form-control-label')}}
                {% if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class='form-control form-control-lg') }}
                {% endif %}
            </div>

            <!-- Confirm Password Field -->

            <div class='form-group'>
                {{form.confirm_password.label(class='form-control-label')}}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                <div class='invalid-feedback'>
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class='form-control form-control-lg') }}
                {% endif %}
            </div>
        </fieldset>

        <!-- Submit Field -->

        <div class='form-group'>
            {{form.submit(class='btn btn-outline-info')}}
        </div>
    </form>
</div>

<div>
  <small class='text-muted'>
     Have An Account? <a class='ml-2' href='{{url_for("users.login")}}'>Login</a>
 </small>
</div>

{% endblock %}




app/templates/user_posts.html
{% extends 'layout.html' %}



{% block content %}
    <h1 class="mb-3">Posts by {{user.username}} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">

	<!-- Aritcle Author Profile Picture -->
	<img class="rounded-circle article-img" src="{{ url_for('static',filename='profile_pics/' + post.author.image_file) }}">
	
	<div class="media-body">

		<div class="article-metadata">

			<!-- Author Name And Post Dated -->
			<a class="mr-2" href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
			<small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>

		</div>

		<!-- Post Title And Content -->
		<h2><a class="article-title" href="{{ url_for('posts.read_post',post_id=post.id) }}">{{ post.title }}</a></h2>
		<p class="article-content">{{ post.content }}</p>
	
	</div>

</article>
{% endfor %}

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
	{% if page_num %}
		{% if posts.page == page_num %}
			<a class="btn btn-info mb-4" href="{{ url_for('posts.user_posts',username=user.username,page=page_num)}}">{{ page_num }}</a>
		{% else %}
			<a class="btn btn-outline-info mb-4" href="{{ url_for('posts.user_posts',username=user.username, page=page_num) }}">{{ page_num }}</a>
		{% endif %}
	{% else %}
	  ...
	{% endif %}
{% endfor %}

{% endblock %}